import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "../styles/Restaurant.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function LoggedIn() {
  const router = useRouter();
  const [restaurantName, setRestaurantName] = useState('');

  useEffect(() => {
    const { restaurant } = router.query;
    if (restaurant) {
      setRestaurantName(decodeURIComponent(restaurant));
    }
  }, [router.query]);

  return (
    <>
      <Head>
        <title>LastBite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <h1 className={styles.restaurantMainHook}>
            {restaurantName ? `You're logged in, ${restaurantName}!` : 'You are not logged in. Return to /restaurants'}
          </h1>
        </div>
      </main>
    </>
  );
}
