import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../styles/Restaurant.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Restaurant() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <h1 className={styles.restaurantMainHook}>
           Welcome to the restaurants page!
          </h1>
          <br />
          <p className={styles.blurb}>LastBite is excited to help bring you more customers, while putting leftovers to good use.</p>
    
        </div>

    
      </main>
    </>
  );
}
